### ISSUE TITLE
Create a setting file that can configure repository, file path, and reference url

### ISSUE THREAD

**Issue by atsushi130** [atsushi130/dotman#1]
example: `setting.toml`
```toml
[repository]
github = "https://raw.githubusercontent.com/atsushi130/dotfiles"

[input]
vimrc = "/vim/.vimrc"
zshrc = "/zsh/.zshrc"
aliasrc = "/.aliasrc"
gitconfig = "/.gitconfig"
gitignore = "/.gitignore"

[output]
vimrc = "~/.vimrc"
zshrc = "~/.zshrc"
aliasrc = "~/.aliasrc"
gitconfig = "~/.gitconfig"
gitignore = "~/.gitignore"
```

OR 

```
{
  "repository": "https://raw.githubusercontent.com/atsushi130/dotfiles",
  "dotfiles": [
    { 
      "name": "vimrc",
      "input": "/vim/.vimrc",
      "output": "~/.vimrc"
    },
    { 
      "name": "zshrc",
      "input": "/zsh/.zshrc",
      "output": "~/.zshrc"
    },
    { 
      "name": "aliasrc",
      "input": "/alias/.aliasrc",
      "output": "~/.aliasrc"
    },
    { 
      "name": "gitconfig",
      "input": "/.gitconfig",
      "output": "~/.gitconfig"
    },
    { 
      "name": "gitignore",
      "input": "/gitignore/.gitignore",
      "output": "~/.gitignore"
    }
  ]
}
```
